version: '3'
services:
  ddddocr-fastapi:
    image: xjxjin/ddddocr-fastapi:sha-ae4ea5b
    restart: always
    container_name: ddddocr-fastapi
    ports:
      - "8081:8000"
    #volumes:
    #  - /home/docker/volumes/ddddocr-fastapi-data/_data:/ddddocr-fastapi-data
    environment:
      - TZ=Asia/Shanghai
      - API_TOKEN=xxxxxx
      - DEBUG=1
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"